data_load:
  dataset_xlsx: 'datasets/onlineretail/online_retail.xlsx'


train: 
  apriori: 
    pruning: 50 
    session_key: 'session_key'
    item_key: 'item_key'
  eclat:
    min_support: 0.0001
    max_items: 4
    min_items: 2


evaluate:
  reports_dir: reports
  metrics_file: 'metrics.json'
  item_hist: 'item_hist.png'
  session_hist: 'session_hist.png'